# Generated by Django 3.2.7 on 2023-03-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrreg',
            name='status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
