# Generated by Django 3.2.7 on 2023-03-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0002_hrreg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('mob', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
