# Generated by Django 3.2.7 on 2023-03-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0003_employeereg'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidatereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('semester', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('image', models.FileField(max_length=150, upload_to='')),
            ],
        ),
    ]
