# Generated by Django 3.2.7 on 2023-03-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0005_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='addjobvacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('venue', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
