# Generated by Django 3.2.7 on 2023-03-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0006_addjobvacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=150)),
                ('university', models.CharField(max_length=150)),
                ('marks', models.CharField(max_length=150)),
                ('qual', models.CharField(max_length=150)),
                ('file', models.FileField(max_length=150, upload_to='')),
                ('university1', models.CharField(max_length=150)),
                ('marks1', models.CharField(max_length=150)),
                ('qual1', models.CharField(max_length=150)),
                ('file1', models.FileField(max_length=150, upload_to='')),
                ('university2', models.CharField(max_length=150)),
                ('marks2', models.CharField(max_length=150)),
                ('qual2', models.CharField(max_length=150)),
                ('file2', models.FileField(max_length=150, upload_to='')),
            ],
        ),
    ]
