# Generated by Django 3.2.7 on 2023-03-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0007_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=150)),
                ('c_email', models.CharField(max_length=150)),
                ('j_id', models.CharField(max_length=150)),
                ('cuname', models.CharField(max_length=150)),
                ('file', models.FileField(max_length=150, upload_to='')),
            ],
        ),
    ]
