# Generated by Django 3.2.7 on 2023-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0010_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=150)),
                ('complaint', models.CharField(max_length=150)),
                ('reply', models.CharField(max_length=150)),
            ],
        ),
    ]
