# Generated by Django 3.2.7 on 2023-03-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0011_complaints_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=150)),
                ('feedback', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
    ]
