# Generated by Django 3.2.7 on 2023-03-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0012_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='placedcandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=150)),
                ('i_id', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('image', models.FileField(max_length=150, upload_to='')),
            ],
        ),
    ]
