# Generated by Django 3.2.7 on 2023-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0013_placedcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('job', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
            ],
        ),
    ]
