# Generated by Django 3.2.7 on 2023-03-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0014_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
