# Generated by Django 3.2.7 on 2023-03-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0015_promotions_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='transfer_dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=150)),
                ('from_id', models.CharField(max_length=150)),
                ('to_id', models.CharField(max_length=150)),
                ('remark', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
