# Generated by Django 3.2.7 on 2023-03-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0016_transfer_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='transfer_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=150)),
                ('from_b', models.CharField(max_length=150)),
                ('to_b', models.CharField(max_length=150)),
                ('remark', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
