# Generated by Django 3.2.7 on 2023-03-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0017_transfer_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
