# Generated by Django 3.2.7 on 2023-03-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0018_tbl_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
