# Generated by Django 3.2.7 on 2023-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0020_jobassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereg',
            name='designation',
            field=models.CharField(default=3, max_length=150),
            preserve_default=False,
        ),
    ]
