# Generated by Django 3.2.7 on 2023-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0021_employeereg_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('basicpay', models.CharField(max_length=150)),
            ],
        ),
    ]
