# Generated by Django 3.2.7 on 2023-03-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0022_basic'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=150)),
            ],
        ),
    ]
