# Generated by Django 3.2.7 on 2023-03-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0023_salary_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_tb',
            name='salary',
            field=models.CharField(default=4, max_length=150),
            preserve_default=False,
        ),
    ]
