# Generated by Django 3.2.7 on 2023-11-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirefellow', '0024_salary_tb_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_attendance',
            name='date',
            field=models.DateField(max_length=150),
        ),
        migrations.AlterField(
            model_name='salary_tb',
            name='month',
            field=models.DateField(max_length=150),
        ),
    ]
